//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EEG_ReelCinemasRESTAPI.Smartbutton.MemberSecurity {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MemberSecuritySoap", Namespace="LoyaltyPlatformWS")]
    public partial class MemberSecurity : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidatePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidatePINOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPINOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePINOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchMemberLastPasswordChangeDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnrollmentVerificationIssueCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailVerificationIssueCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TextVerificationIssueCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnrollmentVerificationSubmitCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailVerificationSubmitCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TextVerificationSubmitCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MemberSecurity() {
            this.Url = global::EEG_ReelCinemasRESTAPI.Properties.Settings.Default.EEG_ReelCinemasRESTAPI_Smartbutton_MemberSecurity_MemberSecurity;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidatePasswordCompletedEventHandler ValidatePasswordCompleted;
        
        /// <remarks/>
        public event SetPasswordCompletedEventHandler SetPasswordCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        public event ValidatePINCompletedEventHandler ValidatePINCompleted;
        
        /// <remarks/>
        public event SetPINCompletedEventHandler SetPINCompleted;
        
        /// <remarks/>
        public event ChangePINCompletedEventHandler ChangePINCompleted;
        
        /// <remarks/>
        public event FetchMemberLastPasswordChangeDateCompletedEventHandler FetchMemberLastPasswordChangeDateCompleted;
        
        /// <remarks/>
        public event EnrollmentVerificationIssueCodeCompletedEventHandler EnrollmentVerificationIssueCodeCompleted;
        
        /// <remarks/>
        public event EmailVerificationIssueCodeCompletedEventHandler EmailVerificationIssueCodeCompleted;
        
        /// <remarks/>
        public event TextVerificationIssueCodeCompletedEventHandler TextVerificationIssueCodeCompleted;
        
        /// <remarks/>
        public event EnrollmentVerificationSubmitCodeCompletedEventHandler EnrollmentVerificationSubmitCodeCompleted;
        
        /// <remarks/>
        public event EmailVerificationSubmitCodeCompletedEventHandler EmailVerificationSubmitCodeCompleted;
        
        /// <remarks/>
        public event TextVerificationSubmitCodeCompletedEventHandler TextVerificationSubmitCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/ValidatePassword", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ValidatePasswordReturn ValidatePassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPassword) {
            object[] results = this.Invoke("ValidatePassword", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberPassword});
            return ((ValidatePasswordReturn)(results[0]));
        }
        
        /// <remarks/>
        public void ValidatePasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPassword) {
            this.ValidatePasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPassword, null);
        }
        
        /// <remarks/>
        public void ValidatePasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPassword, object userState) {
            if ((this.ValidatePasswordOperationCompleted == null)) {
                this.ValidatePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidatePasswordOperationCompleted);
            }
            this.InvokeAsync("ValidatePassword", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberPassword}, this.ValidatePasswordOperationCompleted, userState);
        }
        
        private void OnValidatePasswordOperationCompleted(object arg) {
            if ((this.ValidatePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidatePasswordCompleted(this, new ValidatePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/SetPassword", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetPasswordReturn SetPassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPassword) {
            object[] results = this.Invoke("SetPassword", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberNewPassword});
            return ((SetPasswordReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPassword) {
            this.SetPasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPassword, null);
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPassword, object userState) {
            if ((this.SetPasswordOperationCompleted == null)) {
                this.SetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPasswordOperationCompleted);
            }
            this.InvokeAsync("SetPassword", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberNewPassword}, this.SetPasswordOperationCompleted, userState);
        }
        
        private void OnSetPasswordOperationCompleted(object arg) {
            if ((this.SetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPasswordCompleted(this, new SetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/ChangePassword", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChangePasswordReturn ChangePassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPassword, string MemberNewPassword) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberCurrentPassword,
                        MemberNewPassword});
            return ((ChangePasswordReturn)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPassword, string MemberNewPassword) {
            this.ChangePasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPassword, MemberNewPassword, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPassword, string MemberNewPassword, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberCurrentPassword,
                        MemberNewPassword}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/ValidatePIN", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ValidatePINReturn ValidatePIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPIN) {
            object[] results = this.Invoke("ValidatePIN", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberPIN});
            return ((ValidatePINReturn)(results[0]));
        }
        
        /// <remarks/>
        public void ValidatePINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPIN) {
            this.ValidatePINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPIN, null);
        }
        
        /// <remarks/>
        public void ValidatePINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPIN, object userState) {
            if ((this.ValidatePINOperationCompleted == null)) {
                this.ValidatePINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidatePINOperationCompleted);
            }
            this.InvokeAsync("ValidatePIN", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberPIN}, this.ValidatePINOperationCompleted, userState);
        }
        
        private void OnValidatePINOperationCompleted(object arg) {
            if ((this.ValidatePINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidatePINCompleted(this, new ValidatePINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/SetPIN", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetPINReturn SetPIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPIN) {
            object[] results = this.Invoke("SetPIN", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberNewPIN});
            return ((SetPINReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SetPINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPIN) {
            this.SetPINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPIN, null);
        }
        
        /// <remarks/>
        public void SetPINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPIN, object userState) {
            if ((this.SetPINOperationCompleted == null)) {
                this.SetPINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPINOperationCompleted);
            }
            this.InvokeAsync("SetPIN", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberNewPIN}, this.SetPINOperationCompleted, userState);
        }
        
        private void OnSetPINOperationCompleted(object arg) {
            if ((this.SetPINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPINCompleted(this, new SetPINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/ChangePIN", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChangePINReturn ChangePIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPIN, string MemberNewPIN) {
            object[] results = this.Invoke("ChangePIN", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberCurrentPIN,
                        MemberNewPIN});
            return ((ChangePINReturn)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPIN, string MemberNewPIN) {
            this.ChangePINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPIN, MemberNewPIN, null);
        }
        
        /// <remarks/>
        public void ChangePINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPIN, string MemberNewPIN, object userState) {
            if ((this.ChangePINOperationCompleted == null)) {
                this.ChangePINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePINOperationCompleted);
            }
            this.InvokeAsync("ChangePIN", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberCurrentPIN,
                        MemberNewPIN}, this.ChangePINOperationCompleted, userState);
        }
        
        private void OnChangePINOperationCompleted(object arg) {
            if ((this.ChangePINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePINCompleted(this, new ChangePINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchMemberLastPasswordChangeDate", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchMemberLastPasswordChangeDateReturn FetchMemberLastPasswordChangeDate(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("FetchMemberLastPasswordChangeDate", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((FetchMemberLastPasswordChangeDateReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchMemberLastPasswordChangeDateAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.FetchMemberLastPasswordChangeDateAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void FetchMemberLastPasswordChangeDateAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.FetchMemberLastPasswordChangeDateOperationCompleted == null)) {
                this.FetchMemberLastPasswordChangeDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchMemberLastPasswordChangeDateOperationCompleted);
            }
            this.InvokeAsync("FetchMemberLastPasswordChangeDate", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.FetchMemberLastPasswordChangeDateOperationCompleted, userState);
        }
        
        private void OnFetchMemberLastPasswordChangeDateOperationCompleted(object arg) {
            if ((this.FetchMemberLastPasswordChangeDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchMemberLastPasswordChangeDateCompleted(this, new FetchMemberLastPasswordChangeDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/EnrollmentVerificationIssueCode", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnrollmentVerificationIssueCodeReturn EnrollmentVerificationIssueCode(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("EnrollmentVerificationIssueCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((EnrollmentVerificationIssueCodeReturn)(results[0]));
        }
        
        /// <remarks/>
        public void EnrollmentVerificationIssueCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.EnrollmentVerificationIssueCodeAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void EnrollmentVerificationIssueCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.EnrollmentVerificationIssueCodeOperationCompleted == null)) {
                this.EnrollmentVerificationIssueCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnrollmentVerificationIssueCodeOperationCompleted);
            }
            this.InvokeAsync("EnrollmentVerificationIssueCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.EnrollmentVerificationIssueCodeOperationCompleted, userState);
        }
        
        private void OnEnrollmentVerificationIssueCodeOperationCompleted(object arg) {
            if ((this.EnrollmentVerificationIssueCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnrollmentVerificationIssueCodeCompleted(this, new EnrollmentVerificationIssueCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/EmailVerificationIssueCode", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmailVerificationIssueCodeReturn EmailVerificationIssueCode(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("EmailVerificationIssueCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((EmailVerificationIssueCodeReturn)(results[0]));
        }
        
        /// <remarks/>
        public void EmailVerificationIssueCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.EmailVerificationIssueCodeAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void EmailVerificationIssueCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.EmailVerificationIssueCodeOperationCompleted == null)) {
                this.EmailVerificationIssueCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailVerificationIssueCodeOperationCompleted);
            }
            this.InvokeAsync("EmailVerificationIssueCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.EmailVerificationIssueCodeOperationCompleted, userState);
        }
        
        private void OnEmailVerificationIssueCodeOperationCompleted(object arg) {
            if ((this.EmailVerificationIssueCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailVerificationIssueCodeCompleted(this, new EmailVerificationIssueCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/TextVerificationIssueCode", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TextVerificationIssueCodeReturn TextVerificationIssueCode(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("TextVerificationIssueCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((TextVerificationIssueCodeReturn)(results[0]));
        }
        
        /// <remarks/>
        public void TextVerificationIssueCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.TextVerificationIssueCodeAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void TextVerificationIssueCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.TextVerificationIssueCodeOperationCompleted == null)) {
                this.TextVerificationIssueCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTextVerificationIssueCodeOperationCompleted);
            }
            this.InvokeAsync("TextVerificationIssueCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.TextVerificationIssueCodeOperationCompleted, userState);
        }
        
        private void OnTextVerificationIssueCodeOperationCompleted(object arg) {
            if ((this.TextVerificationIssueCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TextVerificationIssueCodeCompleted(this, new TextVerificationIssueCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/EnrollmentVerificationSubmitCode", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnrollmentVerificationSubmitCodeReturn EnrollmentVerificationSubmitCode(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference) {
            object[] results = this.Invoke("EnrollmentVerificationSubmitCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        VerificationCode,
                        LocationExternalReference});
            return ((EnrollmentVerificationSubmitCodeReturn)(results[0]));
        }
        
        /// <remarks/>
        public void EnrollmentVerificationSubmitCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference) {
            this.EnrollmentVerificationSubmitCodeAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, VerificationCode, LocationExternalReference, null);
        }
        
        /// <remarks/>
        public void EnrollmentVerificationSubmitCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference, object userState) {
            if ((this.EnrollmentVerificationSubmitCodeOperationCompleted == null)) {
                this.EnrollmentVerificationSubmitCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnrollmentVerificationSubmitCodeOperationCompleted);
            }
            this.InvokeAsync("EnrollmentVerificationSubmitCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        VerificationCode,
                        LocationExternalReference}, this.EnrollmentVerificationSubmitCodeOperationCompleted, userState);
        }
        
        private void OnEnrollmentVerificationSubmitCodeOperationCompleted(object arg) {
            if ((this.EnrollmentVerificationSubmitCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnrollmentVerificationSubmitCodeCompleted(this, new EnrollmentVerificationSubmitCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/EmailVerificationSubmitCode", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmailVerificationSubmitCodeReturn EmailVerificationSubmitCode(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference) {
            object[] results = this.Invoke("EmailVerificationSubmitCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        VerificationCode,
                        LocationExternalReference});
            return ((EmailVerificationSubmitCodeReturn)(results[0]));
        }
        
        /// <remarks/>
        public void EmailVerificationSubmitCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference) {
            this.EmailVerificationSubmitCodeAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, VerificationCode, LocationExternalReference, null);
        }
        
        /// <remarks/>
        public void EmailVerificationSubmitCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference, object userState) {
            if ((this.EmailVerificationSubmitCodeOperationCompleted == null)) {
                this.EmailVerificationSubmitCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailVerificationSubmitCodeOperationCompleted);
            }
            this.InvokeAsync("EmailVerificationSubmitCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        VerificationCode,
                        LocationExternalReference}, this.EmailVerificationSubmitCodeOperationCompleted, userState);
        }
        
        private void OnEmailVerificationSubmitCodeOperationCompleted(object arg) {
            if ((this.EmailVerificationSubmitCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailVerificationSubmitCodeCompleted(this, new EmailVerificationSubmitCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/TextVerificationSubmitCode", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TextVerificationSubmitCodeReturn TextVerificationSubmitCode(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference) {
            object[] results = this.Invoke("TextVerificationSubmitCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        VerificationCode,
                        LocationExternalReference});
            return ((TextVerificationSubmitCodeReturn)(results[0]));
        }
        
        /// <remarks/>
        public void TextVerificationSubmitCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference) {
            this.TextVerificationSubmitCodeAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, VerificationCode, LocationExternalReference, null);
        }
        
        /// <remarks/>
        public void TextVerificationSubmitCodeAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string VerificationCode, string LocationExternalReference, object userState) {
            if ((this.TextVerificationSubmitCodeOperationCompleted == null)) {
                this.TextVerificationSubmitCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTextVerificationSubmitCodeOperationCompleted);
            }
            this.InvokeAsync("TextVerificationSubmitCode", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        VerificationCode,
                        LocationExternalReference}, this.TextVerificationSubmitCodeOperationCompleted, userState);
        }
        
        private void OnTextVerificationSubmitCodeOperationCompleted(object arg) {
            if ((this.TextVerificationSubmitCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TextVerificationSubmitCodeCompleted(this, new TextVerificationSubmitCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class ValidatePasswordReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class TextVerificationSubmitCodeReturn {
        
        private int returnCodeField;
        
        private long memberVerificationIdField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public long MemberVerificationId {
            get {
                return this.memberVerificationIdField;
            }
            set {
                this.memberVerificationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class EmailVerificationSubmitCodeReturn {
        
        private int returnCodeField;
        
        private int memberVerificationIdField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MemberVerificationId {
            get {
                return this.memberVerificationIdField;
            }
            set {
                this.memberVerificationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class EnrollmentVerificationSubmitCodeReturn {
        
        private int returnCodeField;
        
        private int memberVerificationIdField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MemberVerificationId {
            get {
                return this.memberVerificationIdField;
            }
            set {
                this.memberVerificationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class TextVerificationIssueCodeReturn {
        
        private int returnCodeField;
        
        private int memberVerificationIdField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MemberVerificationId {
            get {
                return this.memberVerificationIdField;
            }
            set {
                this.memberVerificationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class EmailVerificationIssueCodeReturn {
        
        private int returnCodeField;
        
        private int memberVerificationIdField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MemberVerificationId {
            get {
                return this.memberVerificationIdField;
            }
            set {
                this.memberVerificationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class EnrollmentVerificationIssueCodeReturn {
        
        private int returnCodeField;
        
        private int memberVerificationIdField;
        
        private string contactMethodField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MemberVerificationId {
            get {
                return this.memberVerificationIdField;
            }
            set {
                this.memberVerificationIdField = value;
            }
        }
        
        /// <remarks/>
        public string ContactMethod {
            get {
                return this.contactMethodField;
            }
            set {
                this.contactMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchMemberLastPasswordChangeDateReturn {
        
        private int returnCodeField;
        
        private string lastPasswordChangeTimestampUTCField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LastPasswordChangeTimestampUTC {
            get {
                return this.lastPasswordChangeTimestampUTCField;
            }
            set {
                this.lastPasswordChangeTimestampUTCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class ChangePINReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SetPINReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class ValidatePINReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class ChangePasswordReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SetPasswordReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ValidatePasswordCompletedEventHandler(object sender, ValidatePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidatePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidatePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidatePasswordReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidatePasswordReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SetPasswordCompletedEventHandler(object sender, SetPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetPasswordReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetPasswordReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChangePasswordReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChangePasswordReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ValidatePINCompletedEventHandler(object sender, ValidatePINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidatePINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidatePINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidatePINReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidatePINReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SetPINCompletedEventHandler(object sender, SetPINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetPINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetPINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetPINReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetPINReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ChangePINCompletedEventHandler(object sender, ChangePINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChangePINReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChangePINReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchMemberLastPasswordChangeDateCompletedEventHandler(object sender, FetchMemberLastPasswordChangeDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchMemberLastPasswordChangeDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchMemberLastPasswordChangeDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchMemberLastPasswordChangeDateReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchMemberLastPasswordChangeDateReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void EnrollmentVerificationIssueCodeCompletedEventHandler(object sender, EnrollmentVerificationIssueCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnrollmentVerificationIssueCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnrollmentVerificationIssueCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnrollmentVerificationIssueCodeReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnrollmentVerificationIssueCodeReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void EmailVerificationIssueCodeCompletedEventHandler(object sender, EmailVerificationIssueCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailVerificationIssueCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailVerificationIssueCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmailVerificationIssueCodeReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmailVerificationIssueCodeReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void TextVerificationIssueCodeCompletedEventHandler(object sender, TextVerificationIssueCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TextVerificationIssueCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TextVerificationIssueCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TextVerificationIssueCodeReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TextVerificationIssueCodeReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void EnrollmentVerificationSubmitCodeCompletedEventHandler(object sender, EnrollmentVerificationSubmitCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnrollmentVerificationSubmitCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnrollmentVerificationSubmitCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnrollmentVerificationSubmitCodeReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnrollmentVerificationSubmitCodeReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void EmailVerificationSubmitCodeCompletedEventHandler(object sender, EmailVerificationSubmitCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailVerificationSubmitCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailVerificationSubmitCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmailVerificationSubmitCodeReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmailVerificationSubmitCodeReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void TextVerificationSubmitCodeCompletedEventHandler(object sender, TextVerificationSubmitCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TextVerificationSubmitCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TextVerificationSubmitCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TextVerificationSubmitCodeReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TextVerificationSubmitCodeReturn)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591