//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEG_ReelCinemasRESTAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ca.smartbutton.com/Services/Portal.asmx")]
        public string EEG_ReelCinemasRESTAPI_Smartbutton_Portal_Portal {
            get {
                return ((string)(this["EEG_ReelCinemasRESTAPI_Smartbutton_Portal_Portal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ca.smartbutton.com/WS/Offer.asmx")]
        public string EEG_ReelCinemasRESTAPI_Smartbutton_Offer_Offer {
            get {
                return ((string)(this["EEG_ReelCinemasRESTAPI_Smartbutton_Offer_Offer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ca.smartbutton.com/Services/Reward.asmx")]
        public string EEG_ReelCinemasRESTAPI_Smartbutton_Reward_Reward {
            get {
                return ((string)(this["EEG_ReelCinemasRESTAPI_Smartbutton_Reward_Reward"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ca.smartbutton.com/WS/Transaction.asmx")]
        public string EEG_ReelCinemasRESTAPI_Smartbutton_Transaction_Transaction {
            get {
                return ((string)(this["EEG_ReelCinemasRESTAPI_Smartbutton_Transaction_Transaction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ca.smartbutton.com/WS/MemberActivity.asmx")]
        public string EEG_ReelCinemasRESTAPI_Smartbutton_MemberActivity_MemberActivity {
            get {
                return ((string)(this["EEG_ReelCinemasRESTAPI_Smartbutton_MemberActivity_MemberActivity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ca.smartbutton.com/WS/Member.asmx")]
        public string EEG_ReelCinemasRESTAPI_Smartbutton_Member_Member {
            get {
                return ((string)(this["EEG_ReelCinemasRESTAPI_Smartbutton_Member_Member"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ca.smartbutton.com/WS/MemberContact.asmx")]
        public string EEG_ReelCinemasRESTAPI_Smartbutton_MemberContact_MemberContact {
            get {
                return ((string)(this["EEG_ReelCinemasRESTAPI_Smartbutton_MemberContact_MemberContact"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ca.smartbutton.com/WS/MemberSecurity.asmx")]
        public string EEG_ReelCinemasRESTAPI_Smartbutton_MemberSecurity_MemberSecurity {
            get {
                return ((string)(this["EEG_ReelCinemasRESTAPI_Smartbutton_MemberSecurity_MemberSecurity"]));
            }
        }
    }
}
