//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EEG_ReelCinemasRESTAPI.Smartbutton.Portal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PortalSoap", Namespace="https://app.smartbutton.com/Services/")]
    public partial class Portal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrossLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrossLoginExtOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExternalLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Portal() {
            this.Url = global::EEG_ReelCinemasRESTAPI.Properties.Settings.Default.EEG_ReelCinemasRESTAPI_Smartbutton_Portal_Portal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrossLoginCompletedEventHandler CrossLoginCompleted;
        
        /// <remarks/>
        public event CrossLoginExtCompletedEventHandler CrossLoginExtCompleted;
        
        /// <remarks/>
        public event ExternalLoginCompletedEventHandler ExternalLoginCompleted;
        
        /// <remarks/>
        public event ValidateLoginCompletedEventHandler ValidateLoginCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        public event SetPasswordCompletedEventHandler SetPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://app.smartbutton.com/Services/CrossLogin", RequestNamespace="https://app.smartbutton.com/Services/", ResponseNamespace="https://app.smartbutton.com/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public respCrossLogin CrossLogin(reqCrossLogin preqCrossLogin) {
            object[] results = this.Invoke("CrossLogin", new object[] {
                        preqCrossLogin});
            return ((respCrossLogin)(results[0]));
        }
        
        /// <remarks/>
        public void CrossLoginAsync(reqCrossLogin preqCrossLogin) {
            this.CrossLoginAsync(preqCrossLogin, null);
        }
        
        /// <remarks/>
        public void CrossLoginAsync(reqCrossLogin preqCrossLogin, object userState) {
            if ((this.CrossLoginOperationCompleted == null)) {
                this.CrossLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrossLoginOperationCompleted);
            }
            this.InvokeAsync("CrossLogin", new object[] {
                        preqCrossLogin}, this.CrossLoginOperationCompleted, userState);
        }
        
        private void OnCrossLoginOperationCompleted(object arg) {
            if ((this.CrossLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrossLoginCompleted(this, new CrossLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://app.smartbutton.com/Services/CrossLoginExt", RequestNamespace="https://app.smartbutton.com/Services/", ResponseNamespace="https://app.smartbutton.com/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public respCrossLogin CrossLoginExt(reqCrossLoginExt preqCrossLoginExt) {
            object[] results = this.Invoke("CrossLoginExt", new object[] {
                        preqCrossLoginExt});
            return ((respCrossLogin)(results[0]));
        }
        
        /// <remarks/>
        public void CrossLoginExtAsync(reqCrossLoginExt preqCrossLoginExt) {
            this.CrossLoginExtAsync(preqCrossLoginExt, null);
        }
        
        /// <remarks/>
        public void CrossLoginExtAsync(reqCrossLoginExt preqCrossLoginExt, object userState) {
            if ((this.CrossLoginExtOperationCompleted == null)) {
                this.CrossLoginExtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrossLoginExtOperationCompleted);
            }
            this.InvokeAsync("CrossLoginExt", new object[] {
                        preqCrossLoginExt}, this.CrossLoginExtOperationCompleted, userState);
        }
        
        private void OnCrossLoginExtOperationCompleted(object arg) {
            if ((this.CrossLoginExtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrossLoginExtCompleted(this, new CrossLoginExtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://app.smartbutton.com/Services/ExternalLogin", RequestNamespace="https://app.smartbutton.com/Services/", ResponseNamespace="https://app.smartbutton.com/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public respExternalLogin ExternalLogin(string SecurityToken, string LocationExternalReference, string AccountId, string Password) {
            object[] results = this.Invoke("ExternalLogin", new object[] {
                        SecurityToken,
                        LocationExternalReference,
                        AccountId,
                        Password});
            return ((respExternalLogin)(results[0]));
        }
        
        /// <remarks/>
        public void ExternalLoginAsync(string SecurityToken, string LocationExternalReference, string AccountId, string Password) {
            this.ExternalLoginAsync(SecurityToken, LocationExternalReference, AccountId, Password, null);
        }
        
        /// <remarks/>
        public void ExternalLoginAsync(string SecurityToken, string LocationExternalReference, string AccountId, string Password, object userState) {
            if ((this.ExternalLoginOperationCompleted == null)) {
                this.ExternalLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExternalLoginOperationCompleted);
            }
            this.InvokeAsync("ExternalLogin", new object[] {
                        SecurityToken,
                        LocationExternalReference,
                        AccountId,
                        Password}, this.ExternalLoginOperationCompleted, userState);
        }
        
        private void OnExternalLoginOperationCompleted(object arg) {
            if ((this.ExternalLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExternalLoginCompleted(this, new ExternalLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://app.smartbutton.com/Services/ValidateLogin", RequestNamespace="https://app.smartbutton.com/Services/", ResponseNamespace="https://app.smartbutton.com/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ValidateLogin(string SecurityToken, string AccountId, string Password) {
            object[] results = this.Invoke("ValidateLogin", new object[] {
                        SecurityToken,
                        AccountId,
                        Password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateLoginAsync(string SecurityToken, string AccountId, string Password) {
            this.ValidateLoginAsync(SecurityToken, AccountId, Password, null);
        }
        
        /// <remarks/>
        public void ValidateLoginAsync(string SecurityToken, string AccountId, string Password, object userState) {
            if ((this.ValidateLoginOperationCompleted == null)) {
                this.ValidateLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateLoginOperationCompleted);
            }
            this.InvokeAsync("ValidateLogin", new object[] {
                        SecurityToken,
                        AccountId,
                        Password}, this.ValidateLoginOperationCompleted, userState);
        }
        
        private void OnValidateLoginOperationCompleted(object arg) {
            if ((this.ValidateLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateLoginCompleted(this, new ValidateLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://app.smartbutton.com/Services/ChangePassword", RequestNamespace="https://app.smartbutton.com/Services/", ResponseNamespace="https://app.smartbutton.com/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ChangePassword(string SecurityToken, string AccountId, string ExistingPassword, string NewPassword) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        SecurityToken,
                        AccountId,
                        ExistingPassword,
                        NewPassword});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string SecurityToken, string AccountId, string ExistingPassword, string NewPassword) {
            this.ChangePasswordAsync(SecurityToken, AccountId, ExistingPassword, NewPassword, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string SecurityToken, string AccountId, string ExistingPassword, string NewPassword, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        SecurityToken,
                        AccountId,
                        ExistingPassword,
                        NewPassword}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://app.smartbutton.com/Services/SetPassword", RequestNamespace="https://app.smartbutton.com/Services/", ResponseNamespace="https://app.smartbutton.com/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetPassword(string SecurityToken, string AccountId, string NewPassword) {
            object[] results = this.Invoke("SetPassword", new object[] {
                        SecurityToken,
                        AccountId,
                        NewPassword});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string SecurityToken, string AccountId, string NewPassword) {
            this.SetPasswordAsync(SecurityToken, AccountId, NewPassword, null);
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string SecurityToken, string AccountId, string NewPassword, object userState) {
            if ((this.SetPasswordOperationCompleted == null)) {
                this.SetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPasswordOperationCompleted);
            }
            this.InvokeAsync("SetPassword", new object[] {
                        SecurityToken,
                        AccountId,
                        NewPassword}, this.SetPasswordOperationCompleted, userState);
        }
        
        private void OnSetPasswordOperationCompleted(object arg) {
            if ((this.SetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPasswordCompleted(this, new SetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://app.smartbutton.com/Services/")]
    public partial class reqCrossLogin {
        
        private string securityTokenField;
        
        private string cardNumberField;
        
        private string passwordField;
        
        /// <remarks/>
        public string SecurityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://app.smartbutton.com/Services/")]
    public partial class respExternalLogin {
        
        private int returnCodeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://app.smartbutton.com/Services/")]
    public partial class reqCrossLoginExt {
        
        private string securityTokenField;
        
        private string cardNumberField;
        
        private string passwordField;
        
        private string menuItemExternalReferenceField;
        
        /// <remarks/>
        public string SecurityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string MenuItemExternalReference {
            get {
                return this.menuItemExternalReferenceField;
            }
            set {
                this.menuItemExternalReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://app.smartbutton.com/Services/")]
    public partial class respCrossLogin {
        
        private int returnCodeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string crossLoginLinkField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string CrossLoginLink {
            get {
                return this.crossLoginLinkField;
            }
            set {
                this.crossLoginLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void CrossLoginCompletedEventHandler(object sender, CrossLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrossLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrossLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respCrossLogin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respCrossLogin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void CrossLoginExtCompletedEventHandler(object sender, CrossLoginExtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrossLoginExtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrossLoginExtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respCrossLogin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respCrossLogin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ExternalLoginCompletedEventHandler(object sender, ExternalLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExternalLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExternalLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respExternalLogin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respExternalLogin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ValidateLoginCompletedEventHandler(object sender, ValidateLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SetPasswordCompletedEventHandler(object sender, SetPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591