//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EEG_ReelCinemasRESTAPI.Smartbutton.MemberContact {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MemberContactSoap", Namespace="LoyaltyPlatformWS")]
    public partial class MemberContact : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FetchMemberAccountPhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchMemberMobilePhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchMemberPhoneNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchMemberEmailAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchAddressCountryListOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchAddressRegionListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMemberEmailAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMemberAccountPhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMemberMobilePhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMemberPhoneNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchMemberPostalAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchMemberContactInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMemberPostalAddressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MemberContact() {
            this.Url = global::EEG_ReelCinemasRESTAPI.Properties.Settings.Default.EEG_ReelCinemasRESTAPI_Smartbutton_MemberContact_MemberContact;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FetchMemberAccountPhoneNumberCompletedEventHandler FetchMemberAccountPhoneNumberCompleted;
        
        /// <remarks/>
        public event FetchMemberMobilePhoneNumberCompletedEventHandler FetchMemberMobilePhoneNumberCompleted;
        
        /// <remarks/>
        public event FetchMemberPhoneNumbersCompletedEventHandler FetchMemberPhoneNumbersCompleted;
        
        /// <remarks/>
        public event FetchMemberEmailAddressCompletedEventHandler FetchMemberEmailAddressCompleted;
        
        /// <remarks/>
        public event FetchAddressCountryListCompletedEventHandler FetchAddressCountryListCompleted;
        
        /// <remarks/>
        public event FetchAddressRegionListCompletedEventHandler FetchAddressRegionListCompleted;
        
        /// <remarks/>
        public event SaveMemberEmailAddressCompletedEventHandler SaveMemberEmailAddressCompleted;
        
        /// <remarks/>
        public event SaveMemberAccountPhoneNumberCompletedEventHandler SaveMemberAccountPhoneNumberCompleted;
        
        /// <remarks/>
        public event SaveMemberMobilePhoneNumberCompletedEventHandler SaveMemberMobilePhoneNumberCompleted;
        
        /// <remarks/>
        public event SaveMemberPhoneNumbersCompletedEventHandler SaveMemberPhoneNumbersCompleted;
        
        /// <remarks/>
        public event FetchMemberPostalAddressCompletedEventHandler FetchMemberPostalAddressCompleted;
        
        /// <remarks/>
        public event FetchMemberContactInfoCompletedEventHandler FetchMemberContactInfoCompleted;
        
        /// <remarks/>
        public event SaveMemberPostalAddressCompletedEventHandler SaveMemberPostalAddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchMemberAccountPhoneNumber", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchMemberAccountPhoneNumberReturn FetchMemberAccountPhoneNumber(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("FetchMemberAccountPhoneNumber", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((FetchMemberAccountPhoneNumberReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchMemberAccountPhoneNumberAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.FetchMemberAccountPhoneNumberAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void FetchMemberAccountPhoneNumberAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.FetchMemberAccountPhoneNumberOperationCompleted == null)) {
                this.FetchMemberAccountPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchMemberAccountPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("FetchMemberAccountPhoneNumber", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.FetchMemberAccountPhoneNumberOperationCompleted, userState);
        }
        
        private void OnFetchMemberAccountPhoneNumberOperationCompleted(object arg) {
            if ((this.FetchMemberAccountPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchMemberAccountPhoneNumberCompleted(this, new FetchMemberAccountPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchMemberMobilePhoneNumber", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchMemberMobilePhoneNumberReturn FetchMemberMobilePhoneNumber(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("FetchMemberMobilePhoneNumber", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((FetchMemberMobilePhoneNumberReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchMemberMobilePhoneNumberAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.FetchMemberMobilePhoneNumberAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void FetchMemberMobilePhoneNumberAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.FetchMemberMobilePhoneNumberOperationCompleted == null)) {
                this.FetchMemberMobilePhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchMemberMobilePhoneNumberOperationCompleted);
            }
            this.InvokeAsync("FetchMemberMobilePhoneNumber", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.FetchMemberMobilePhoneNumberOperationCompleted, userState);
        }
        
        private void OnFetchMemberMobilePhoneNumberOperationCompleted(object arg) {
            if ((this.FetchMemberMobilePhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchMemberMobilePhoneNumberCompleted(this, new FetchMemberMobilePhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchMemberPhoneNumbers", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchMemberPhoneNumbersReturn FetchMemberPhoneNumbers(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("FetchMemberPhoneNumbers", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((FetchMemberPhoneNumbersReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchMemberPhoneNumbersAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.FetchMemberPhoneNumbersAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void FetchMemberPhoneNumbersAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.FetchMemberPhoneNumbersOperationCompleted == null)) {
                this.FetchMemberPhoneNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchMemberPhoneNumbersOperationCompleted);
            }
            this.InvokeAsync("FetchMemberPhoneNumbers", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.FetchMemberPhoneNumbersOperationCompleted, userState);
        }
        
        private void OnFetchMemberPhoneNumbersOperationCompleted(object arg) {
            if ((this.FetchMemberPhoneNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchMemberPhoneNumbersCompleted(this, new FetchMemberPhoneNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchMemberEmailAddress", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchMemberEmailAddressReturn FetchMemberEmailAddress(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("FetchMemberEmailAddress", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((FetchMemberEmailAddressReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchMemberEmailAddressAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.FetchMemberEmailAddressAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void FetchMemberEmailAddressAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.FetchMemberEmailAddressOperationCompleted == null)) {
                this.FetchMemberEmailAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchMemberEmailAddressOperationCompleted);
            }
            this.InvokeAsync("FetchMemberEmailAddress", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.FetchMemberEmailAddressOperationCompleted, userState);
        }
        
        private void OnFetchMemberEmailAddressOperationCompleted(object arg) {
            if ((this.FetchMemberEmailAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchMemberEmailAddressCompleted(this, new FetchMemberEmailAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchAddressCountryList", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchAddressCountryListReturn FetchAddressCountryList(string WSSecurityToken) {
            object[] results = this.Invoke("FetchAddressCountryList", new object[] {
                        WSSecurityToken});
            return ((FetchAddressCountryListReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchAddressCountryListAsync(string WSSecurityToken) {
            this.FetchAddressCountryListAsync(WSSecurityToken, null);
        }
        
        /// <remarks/>
        public void FetchAddressCountryListAsync(string WSSecurityToken, object userState) {
            if ((this.FetchAddressCountryListOperationCompleted == null)) {
                this.FetchAddressCountryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchAddressCountryListOperationCompleted);
            }
            this.InvokeAsync("FetchAddressCountryList", new object[] {
                        WSSecurityToken}, this.FetchAddressCountryListOperationCompleted, userState);
        }
        
        private void OnFetchAddressCountryListOperationCompleted(object arg) {
            if ((this.FetchAddressCountryListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchAddressCountryListCompleted(this, new FetchAddressCountryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchAddressRegionList", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchAddressRegionListReturn FetchAddressRegionList(string WSSecurityToken, int CountryItemInternalId) {
            object[] results = this.Invoke("FetchAddressRegionList", new object[] {
                        WSSecurityToken,
                        CountryItemInternalId});
            return ((FetchAddressRegionListReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchAddressRegionListAsync(string WSSecurityToken, int CountryItemInternalId) {
            this.FetchAddressRegionListAsync(WSSecurityToken, CountryItemInternalId, null);
        }
        
        /// <remarks/>
        public void FetchAddressRegionListAsync(string WSSecurityToken, int CountryItemInternalId, object userState) {
            if ((this.FetchAddressRegionListOperationCompleted == null)) {
                this.FetchAddressRegionListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchAddressRegionListOperationCompleted);
            }
            this.InvokeAsync("FetchAddressRegionList", new object[] {
                        WSSecurityToken,
                        CountryItemInternalId}, this.FetchAddressRegionListOperationCompleted, userState);
        }
        
        private void OnFetchAddressRegionListOperationCompleted(object arg) {
            if ((this.FetchAddressRegionListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchAddressRegionListCompleted(this, new FetchAddressRegionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/SaveMemberEmailAddress", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SaveMemberEmailAddressReturn SaveMemberEmailAddress(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberEmailAddress, int MemberEmailAddressIsValid) {
            object[] results = this.Invoke("SaveMemberEmailAddress", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberEmailAddress,
                        MemberEmailAddressIsValid});
            return ((SaveMemberEmailAddressReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMemberEmailAddressAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberEmailAddress, int MemberEmailAddressIsValid) {
            this.SaveMemberEmailAddressAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberEmailAddress, MemberEmailAddressIsValid, null);
        }
        
        /// <remarks/>
        public void SaveMemberEmailAddressAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberEmailAddress, int MemberEmailAddressIsValid, object userState) {
            if ((this.SaveMemberEmailAddressOperationCompleted == null)) {
                this.SaveMemberEmailAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMemberEmailAddressOperationCompleted);
            }
            this.InvokeAsync("SaveMemberEmailAddress", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberEmailAddress,
                        MemberEmailAddressIsValid}, this.SaveMemberEmailAddressOperationCompleted, userState);
        }
        
        private void OnSaveMemberEmailAddressOperationCompleted(object arg) {
            if ((this.SaveMemberEmailAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMemberEmailAddressCompleted(this, new SaveMemberEmailAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/SaveMemberAccountPhoneNumber", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SaveMemberAccountPhoneNumberReturn SaveMemberAccountPhoneNumber(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberAccountPhoneNumber, string MemberAccountPhoneNumberExtension, int MemberAccountPhoneNumberIsValid) {
            object[] results = this.Invoke("SaveMemberAccountPhoneNumber", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberAccountPhoneNumber,
                        MemberAccountPhoneNumberExtension,
                        MemberAccountPhoneNumberIsValid});
            return ((SaveMemberAccountPhoneNumberReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMemberAccountPhoneNumberAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberAccountPhoneNumber, string MemberAccountPhoneNumberExtension, int MemberAccountPhoneNumberIsValid) {
            this.SaveMemberAccountPhoneNumberAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberAccountPhoneNumber, MemberAccountPhoneNumberExtension, MemberAccountPhoneNumberIsValid, null);
        }
        
        /// <remarks/>
        public void SaveMemberAccountPhoneNumberAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberAccountPhoneNumber, string MemberAccountPhoneNumberExtension, int MemberAccountPhoneNumberIsValid, object userState) {
            if ((this.SaveMemberAccountPhoneNumberOperationCompleted == null)) {
                this.SaveMemberAccountPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMemberAccountPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("SaveMemberAccountPhoneNumber", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberAccountPhoneNumber,
                        MemberAccountPhoneNumberExtension,
                        MemberAccountPhoneNumberIsValid}, this.SaveMemberAccountPhoneNumberOperationCompleted, userState);
        }
        
        private void OnSaveMemberAccountPhoneNumberOperationCompleted(object arg) {
            if ((this.SaveMemberAccountPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMemberAccountPhoneNumberCompleted(this, new SaveMemberAccountPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/SaveMemberMobilePhoneNumber", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SaveMemberMobilePhoneNumberReturn SaveMemberMobilePhoneNumber(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberMobilePhoneNumber, int MemberMobilePhoneNumberIsValid) {
            object[] results = this.Invoke("SaveMemberMobilePhoneNumber", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberMobilePhoneNumber,
                        MemberMobilePhoneNumberIsValid});
            return ((SaveMemberMobilePhoneNumberReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMemberMobilePhoneNumberAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberMobilePhoneNumber, int MemberMobilePhoneNumberIsValid) {
            this.SaveMemberMobilePhoneNumberAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberMobilePhoneNumber, MemberMobilePhoneNumberIsValid, null);
        }
        
        /// <remarks/>
        public void SaveMemberMobilePhoneNumberAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberMobilePhoneNumber, int MemberMobilePhoneNumberIsValid, object userState) {
            if ((this.SaveMemberMobilePhoneNumberOperationCompleted == null)) {
                this.SaveMemberMobilePhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMemberMobilePhoneNumberOperationCompleted);
            }
            this.InvokeAsync("SaveMemberMobilePhoneNumber", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberMobilePhoneNumber,
                        MemberMobilePhoneNumberIsValid}, this.SaveMemberMobilePhoneNumberOperationCompleted, userState);
        }
        
        private void OnSaveMemberMobilePhoneNumberOperationCompleted(object arg) {
            if ((this.SaveMemberMobilePhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMemberMobilePhoneNumberCompleted(this, new SaveMemberMobilePhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/SaveMemberPhoneNumbers", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SaveMemberPhoneNumbersReturn SaveMemberPhoneNumbers(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberAccountPhoneNumber, string MemberAccountPhoneNumberExtension, int MemberAccountPhoneNumberIsValid, string MemberMobilePhoneNumber, int MemberMobilePhoneNumberIsValid) {
            object[] results = this.Invoke("SaveMemberPhoneNumbers", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberAccountPhoneNumber,
                        MemberAccountPhoneNumberExtension,
                        MemberAccountPhoneNumberIsValid,
                        MemberMobilePhoneNumber,
                        MemberMobilePhoneNumberIsValid});
            return ((SaveMemberPhoneNumbersReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMemberPhoneNumbersAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberAccountPhoneNumber, string MemberAccountPhoneNumberExtension, int MemberAccountPhoneNumberIsValid, string MemberMobilePhoneNumber, int MemberMobilePhoneNumberIsValid) {
            this.SaveMemberPhoneNumbersAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberAccountPhoneNumber, MemberAccountPhoneNumberExtension, MemberAccountPhoneNumberIsValid, MemberMobilePhoneNumber, MemberMobilePhoneNumberIsValid, null);
        }
        
        /// <remarks/>
        public void SaveMemberPhoneNumbersAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberAccountPhoneNumber, string MemberAccountPhoneNumberExtension, int MemberAccountPhoneNumberIsValid, string MemberMobilePhoneNumber, int MemberMobilePhoneNumberIsValid, object userState) {
            if ((this.SaveMemberPhoneNumbersOperationCompleted == null)) {
                this.SaveMemberPhoneNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMemberPhoneNumbersOperationCompleted);
            }
            this.InvokeAsync("SaveMemberPhoneNumbers", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        MemberAccountPhoneNumber,
                        MemberAccountPhoneNumberExtension,
                        MemberAccountPhoneNumberIsValid,
                        MemberMobilePhoneNumber,
                        MemberMobilePhoneNumberIsValid}, this.SaveMemberPhoneNumbersOperationCompleted, userState);
        }
        
        private void OnSaveMemberPhoneNumbersOperationCompleted(object arg) {
            if ((this.SaveMemberPhoneNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMemberPhoneNumbersCompleted(this, new SaveMemberPhoneNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchMemberPostalAddress", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchMemberPostalAddressReturn FetchMemberPostalAddress(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("FetchMemberPostalAddress", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((FetchMemberPostalAddressReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchMemberPostalAddressAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.FetchMemberPostalAddressAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void FetchMemberPostalAddressAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.FetchMemberPostalAddressOperationCompleted == null)) {
                this.FetchMemberPostalAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchMemberPostalAddressOperationCompleted);
            }
            this.InvokeAsync("FetchMemberPostalAddress", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.FetchMemberPostalAddressOperationCompleted, userState);
        }
        
        private void OnFetchMemberPostalAddressOperationCompleted(object arg) {
            if ((this.FetchMemberPostalAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchMemberPostalAddressCompleted(this, new FetchMemberPostalAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/FetchMemberContactInfo", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchMemberContactInfoReturn FetchMemberContactInfo(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            object[] results = this.Invoke("FetchMemberContactInfo", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId});
            return ((FetchMemberContactInfoReturn)(results[0]));
        }
        
        /// <remarks/>
        public void FetchMemberContactInfoAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId) {
            this.FetchMemberContactInfoAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, null);
        }
        
        /// <remarks/>
        public void FetchMemberContactInfoAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, object userState) {
            if ((this.FetchMemberContactInfoOperationCompleted == null)) {
                this.FetchMemberContactInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchMemberContactInfoOperationCompleted);
            }
            this.InvokeAsync("FetchMemberContactInfo", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId}, this.FetchMemberContactInfoOperationCompleted, userState);
        }
        
        private void OnFetchMemberContactInfoOperationCompleted(object arg) {
            if ((this.FetchMemberContactInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchMemberContactInfoCompleted(this, new FetchMemberContactInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoyaltyPlatformWS/SaveMemberPostalAddress", RequestNamespace="LoyaltyPlatformWS", ResponseNamespace="LoyaltyPlatformWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SaveMemberPostalAddressReturn SaveMemberPostalAddress(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, int CountryItemInternalId, string AddressLineCareOf, string AddressLine1, string AddressLine2, string AddressCity, int RegionItemInternalId, string RegionItemFullName, string AddressPostalCode, int MemberAddressIsValid) {
            object[] results = this.Invoke("SaveMemberPostalAddress", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        CountryItemInternalId,
                        AddressLineCareOf,
                        AddressLine1,
                        AddressLine2,
                        AddressCity,
                        RegionItemInternalId,
                        RegionItemFullName,
                        AddressPostalCode,
                        MemberAddressIsValid});
            return ((SaveMemberPostalAddressReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMemberPostalAddressAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, int CountryItemInternalId, string AddressLineCareOf, string AddressLine1, string AddressLine2, string AddressCity, int RegionItemInternalId, string RegionItemFullName, string AddressPostalCode, int MemberAddressIsValid) {
            this.SaveMemberPostalAddressAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, CountryItemInternalId, AddressLineCareOf, AddressLine1, AddressLine2, AddressCity, RegionItemInternalId, RegionItemFullName, AddressPostalCode, MemberAddressIsValid, null);
        }
        
        /// <remarks/>
        public void SaveMemberPostalAddressAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, int CountryItemInternalId, string AddressLineCareOf, string AddressLine1, string AddressLine2, string AddressCity, int RegionItemInternalId, string RegionItemFullName, string AddressPostalCode, int MemberAddressIsValid, object userState) {
            if ((this.SaveMemberPostalAddressOperationCompleted == null)) {
                this.SaveMemberPostalAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMemberPostalAddressOperationCompleted);
            }
            this.InvokeAsync("SaveMemberPostalAddress", new object[] {
                        WSSecurityToken,
                        MemberAccountId,
                        SBInternalMemberId,
                        CountryItemInternalId,
                        AddressLineCareOf,
                        AddressLine1,
                        AddressLine2,
                        AddressCity,
                        RegionItemInternalId,
                        RegionItemFullName,
                        AddressPostalCode,
                        MemberAddressIsValid}, this.SaveMemberPostalAddressOperationCompleted, userState);
        }
        
        private void OnSaveMemberPostalAddressOperationCompleted(object arg) {
            if ((this.SaveMemberPostalAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMemberPostalAddressCompleted(this, new SaveMemberPostalAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchMemberAccountPhoneNumberReturn {
        
        private int returnCodeField;
        
        private int sBInternalMemberIdField;
        
        private string memberAccountPhoneNumberFormattedField;
        
        private string memberAccountPhoneNumberRawField;
        
        private string memberAccountPhoneNumberExtensionField;
        
        private int memberAccountPhoneNumberIsValidField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SBInternalMemberId {
            get {
                return this.sBInternalMemberIdField;
            }
            set {
                this.sBInternalMemberIdField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberFormatted {
            get {
                return this.memberAccountPhoneNumberFormattedField;
            }
            set {
                this.memberAccountPhoneNumberFormattedField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberRaw {
            get {
                return this.memberAccountPhoneNumberRawField;
            }
            set {
                this.memberAccountPhoneNumberRawField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberExtension {
            get {
                return this.memberAccountPhoneNumberExtensionField;
            }
            set {
                this.memberAccountPhoneNumberExtensionField = value;
            }
        }
        
        /// <remarks/>
        public int MemberAccountPhoneNumberIsValid {
            get {
                return this.memberAccountPhoneNumberIsValidField;
            }
            set {
                this.memberAccountPhoneNumberIsValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SaveMemberPostalAddressReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchMemberContactInfoReturn {
        
        private int returnCodeField;
        
        private int sBInternalMemberIdField;
        
        private string memberAccountPhoneNumberFormattedField;
        
        private string memberAccountPhoneNumberRawField;
        
        private string memberAccountPhoneNumberExtensionField;
        
        private int memberAccountPhoneNumberIsValidField;
        
        private string memberMobilePhoneNumberFormattedField;
        
        private string memberMobilePhoneNumberRawField;
        
        private int memberMobilePhoneNumberIsValidField;
        
        private string memberEmailAddressField;
        
        private int memberEmailAddressIsValidField;
        
        private int countryItemInternalIdField;
        
        private string countryItemFullNameField;
        
        private string countryItemAbbreviationField;
        
        private string addressLineCareOfField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressCityField;
        
        private string addressPostalCodeField;
        
        private int regionItemInternalIdField;
        
        private string regionItemFullNameField;
        
        private string regionItemAbbreviationField;
        
        private int addressIsValidField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SBInternalMemberId {
            get {
                return this.sBInternalMemberIdField;
            }
            set {
                this.sBInternalMemberIdField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberFormatted {
            get {
                return this.memberAccountPhoneNumberFormattedField;
            }
            set {
                this.memberAccountPhoneNumberFormattedField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberRaw {
            get {
                return this.memberAccountPhoneNumberRawField;
            }
            set {
                this.memberAccountPhoneNumberRawField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberExtension {
            get {
                return this.memberAccountPhoneNumberExtensionField;
            }
            set {
                this.memberAccountPhoneNumberExtensionField = value;
            }
        }
        
        /// <remarks/>
        public int MemberAccountPhoneNumberIsValid {
            get {
                return this.memberAccountPhoneNumberIsValidField;
            }
            set {
                this.memberAccountPhoneNumberIsValidField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberFormatted {
            get {
                return this.memberMobilePhoneNumberFormattedField;
            }
            set {
                this.memberMobilePhoneNumberFormattedField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberRaw {
            get {
                return this.memberMobilePhoneNumberRawField;
            }
            set {
                this.memberMobilePhoneNumberRawField = value;
            }
        }
        
        /// <remarks/>
        public int MemberMobilePhoneNumberIsValid {
            get {
                return this.memberMobilePhoneNumberIsValidField;
            }
            set {
                this.memberMobilePhoneNumberIsValidField = value;
            }
        }
        
        /// <remarks/>
        public string MemberEmailAddress {
            get {
                return this.memberEmailAddressField;
            }
            set {
                this.memberEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public int MemberEmailAddressIsValid {
            get {
                return this.memberEmailAddressIsValidField;
            }
            set {
                this.memberEmailAddressIsValidField = value;
            }
        }
        
        /// <remarks/>
        public int CountryItemInternalId {
            get {
                return this.countryItemInternalIdField;
            }
            set {
                this.countryItemInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public string CountryItemFullName {
            get {
                return this.countryItemFullNameField;
            }
            set {
                this.countryItemFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string CountryItemAbbreviation {
            get {
                return this.countryItemAbbreviationField;
            }
            set {
                this.countryItemAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLineCareOf {
            get {
                return this.addressLineCareOfField;
            }
            set {
                this.addressLineCareOfField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressCity {
            get {
                return this.addressCityField;
            }
            set {
                this.addressCityField = value;
            }
        }
        
        /// <remarks/>
        public string AddressPostalCode {
            get {
                return this.addressPostalCodeField;
            }
            set {
                this.addressPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public int RegionItemInternalId {
            get {
                return this.regionItemInternalIdField;
            }
            set {
                this.regionItemInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public string RegionItemFullName {
            get {
                return this.regionItemFullNameField;
            }
            set {
                this.regionItemFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string RegionItemAbbreviation {
            get {
                return this.regionItemAbbreviationField;
            }
            set {
                this.regionItemAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        public int AddressIsValid {
            get {
                return this.addressIsValidField;
            }
            set {
                this.addressIsValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchMemberPostalAddressReturn {
        
        private int returnCodeField;
        
        private int sBInternalMemberIdField;
        
        private int countryItemInternalIdField;
        
        private string countryItemFullNameField;
        
        private string countryItemAbbreviationField;
        
        private string addressLineCareOfField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressCityField;
        
        private string addressPostalCodeField;
        
        private int regionItemInternalIdField;
        
        private string regionItemFullNameField;
        
        private string regionItemAbbreviationField;
        
        private int addressIsValidField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SBInternalMemberId {
            get {
                return this.sBInternalMemberIdField;
            }
            set {
                this.sBInternalMemberIdField = value;
            }
        }
        
        /// <remarks/>
        public int CountryItemInternalId {
            get {
                return this.countryItemInternalIdField;
            }
            set {
                this.countryItemInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public string CountryItemFullName {
            get {
                return this.countryItemFullNameField;
            }
            set {
                this.countryItemFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string CountryItemAbbreviation {
            get {
                return this.countryItemAbbreviationField;
            }
            set {
                this.countryItemAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLineCareOf {
            get {
                return this.addressLineCareOfField;
            }
            set {
                this.addressLineCareOfField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressCity {
            get {
                return this.addressCityField;
            }
            set {
                this.addressCityField = value;
            }
        }
        
        /// <remarks/>
        public string AddressPostalCode {
            get {
                return this.addressPostalCodeField;
            }
            set {
                this.addressPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public int RegionItemInternalId {
            get {
                return this.regionItemInternalIdField;
            }
            set {
                this.regionItemInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public string RegionItemFullName {
            get {
                return this.regionItemFullNameField;
            }
            set {
                this.regionItemFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string RegionItemAbbreviation {
            get {
                return this.regionItemAbbreviationField;
            }
            set {
                this.regionItemAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        public int AddressIsValid {
            get {
                return this.addressIsValidField;
            }
            set {
                this.addressIsValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SaveMemberPhoneNumbersReturn {
        
        private int accountPhoneNumberReturnCodeField;
        
        private int mobilePhoneNumberReturnCodeField;
        
        /// <remarks/>
        public int AccountPhoneNumberReturnCode {
            get {
                return this.accountPhoneNumberReturnCodeField;
            }
            set {
                this.accountPhoneNumberReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MobilePhoneNumberReturnCode {
            get {
                return this.mobilePhoneNumberReturnCodeField;
            }
            set {
                this.mobilePhoneNumberReturnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SaveMemberMobilePhoneNumberReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SaveMemberAccountPhoneNumberReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SaveMemberEmailAddressReturn {
        
        private int returnCodeField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class RegionListItem {
        
        private int countryItemInternalIdField;
        
        private int regionItemInternalIdField;
        
        private string regionItemFullNameField;
        
        private string regionItemAbbreviationField;
        
        /// <remarks/>
        public int CountryItemInternalId {
            get {
                return this.countryItemInternalIdField;
            }
            set {
                this.countryItemInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public int RegionItemInternalId {
            get {
                return this.regionItemInternalIdField;
            }
            set {
                this.regionItemInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public string RegionItemFullName {
            get {
                return this.regionItemFullNameField;
            }
            set {
                this.regionItemFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string RegionItemAbbreviation {
            get {
                return this.regionItemAbbreviationField;
            }
            set {
                this.regionItemAbbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchAddressRegionListReturn {
        
        private int returnCodeField;
        
        private RegionListItem[] addressRegionListField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public RegionListItem[] AddressRegionList {
            get {
                return this.addressRegionListField;
            }
            set {
                this.addressRegionListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class CountryListItem {
        
        private int countryItemInternalIdField;
        
        private string countryItemFullNameField;
        
        private string countryItemAbbreviationField;
        
        private string countryItemRegionLabelField;
        
        private string countryItemZipLabelField;
        
        private int countryItemHasDefinedRegionsField;
        
        /// <remarks/>
        public int CountryItemInternalId {
            get {
                return this.countryItemInternalIdField;
            }
            set {
                this.countryItemInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public string CountryItemFullName {
            get {
                return this.countryItemFullNameField;
            }
            set {
                this.countryItemFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string CountryItemAbbreviation {
            get {
                return this.countryItemAbbreviationField;
            }
            set {
                this.countryItemAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        public string CountryItemRegionLabel {
            get {
                return this.countryItemRegionLabelField;
            }
            set {
                this.countryItemRegionLabelField = value;
            }
        }
        
        /// <remarks/>
        public string CountryItemZipLabel {
            get {
                return this.countryItemZipLabelField;
            }
            set {
                this.countryItemZipLabelField = value;
            }
        }
        
        /// <remarks/>
        public int CountryItemHasDefinedRegions {
            get {
                return this.countryItemHasDefinedRegionsField;
            }
            set {
                this.countryItemHasDefinedRegionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchAddressCountryListReturn {
        
        private int returnCodeField;
        
        private CountryListItem[] addressCountryListField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public CountryListItem[] AddressCountryList {
            get {
                return this.addressCountryListField;
            }
            set {
                this.addressCountryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchMemberEmailAddressReturn {
        
        private int returnCodeField;
        
        private int sBInternalMemberIdField;
        
        private string memberEmailAddressField;
        
        private int memberEmailAddressIsValidField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SBInternalMemberId {
            get {
                return this.sBInternalMemberIdField;
            }
            set {
                this.sBInternalMemberIdField = value;
            }
        }
        
        /// <remarks/>
        public string MemberEmailAddress {
            get {
                return this.memberEmailAddressField;
            }
            set {
                this.memberEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public int MemberEmailAddressIsValid {
            get {
                return this.memberEmailAddressIsValidField;
            }
            set {
                this.memberEmailAddressIsValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchMemberPhoneNumbersReturn {
        
        private int returnCodeField;
        
        private int sBInternalMemberIdField;
        
        private string memberAccountPhoneNumberFormattedField;
        
        private string memberAccountPhoneNumberRawField;
        
        private string memberAccountPhoneNumberExtensionField;
        
        private int memberAccountPhoneNumberIsValidField;
        
        private string memberMobilePhoneNumberFormattedField;
        
        private string memberMobilePhoneNumberRawField;
        
        private string memberMobilePhoneNumberMobileCarrierNameField;
        
        private string memberMobilePhoneNumberMobileCarrierInternalIdField;
        
        private int memberMobilePhoneNumberIsValidField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SBInternalMemberId {
            get {
                return this.sBInternalMemberIdField;
            }
            set {
                this.sBInternalMemberIdField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberFormatted {
            get {
                return this.memberAccountPhoneNumberFormattedField;
            }
            set {
                this.memberAccountPhoneNumberFormattedField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberRaw {
            get {
                return this.memberAccountPhoneNumberRawField;
            }
            set {
                this.memberAccountPhoneNumberRawField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAccountPhoneNumberExtension {
            get {
                return this.memberAccountPhoneNumberExtensionField;
            }
            set {
                this.memberAccountPhoneNumberExtensionField = value;
            }
        }
        
        /// <remarks/>
        public int MemberAccountPhoneNumberIsValid {
            get {
                return this.memberAccountPhoneNumberIsValidField;
            }
            set {
                this.memberAccountPhoneNumberIsValidField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberFormatted {
            get {
                return this.memberMobilePhoneNumberFormattedField;
            }
            set {
                this.memberMobilePhoneNumberFormattedField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberRaw {
            get {
                return this.memberMobilePhoneNumberRawField;
            }
            set {
                this.memberMobilePhoneNumberRawField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberMobileCarrierName {
            get {
                return this.memberMobilePhoneNumberMobileCarrierNameField;
            }
            set {
                this.memberMobilePhoneNumberMobileCarrierNameField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberMobileCarrierInternalId {
            get {
                return this.memberMobilePhoneNumberMobileCarrierInternalIdField;
            }
            set {
                this.memberMobilePhoneNumberMobileCarrierInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public int MemberMobilePhoneNumberIsValid {
            get {
                return this.memberMobilePhoneNumberIsValidField;
            }
            set {
                this.memberMobilePhoneNumberIsValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class FetchMemberMobilePhoneNumberReturn {
        
        private int returnCodeField;
        
        private int sBInternalMemberIdField;
        
        private string memberMobilePhoneNumberFormattedField;
        
        private string memberMobilePhoneNumberRawField;
        
        private string memberMobilePhoneNumberMobileCarrierNameField;
        
        private string memberMobilePhoneNumberMobileCarrierInternalIdField;
        
        private int memberMobilePhoneNumberIsValidField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SBInternalMemberId {
            get {
                return this.sBInternalMemberIdField;
            }
            set {
                this.sBInternalMemberIdField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberFormatted {
            get {
                return this.memberMobilePhoneNumberFormattedField;
            }
            set {
                this.memberMobilePhoneNumberFormattedField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberRaw {
            get {
                return this.memberMobilePhoneNumberRawField;
            }
            set {
                this.memberMobilePhoneNumberRawField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberMobileCarrierName {
            get {
                return this.memberMobilePhoneNumberMobileCarrierNameField;
            }
            set {
                this.memberMobilePhoneNumberMobileCarrierNameField = value;
            }
        }
        
        /// <remarks/>
        public string MemberMobilePhoneNumberMobileCarrierInternalId {
            get {
                return this.memberMobilePhoneNumberMobileCarrierInternalIdField;
            }
            set {
                this.memberMobilePhoneNumberMobileCarrierInternalIdField = value;
            }
        }
        
        /// <remarks/>
        public int MemberMobilePhoneNumberIsValid {
            get {
                return this.memberMobilePhoneNumberIsValidField;
            }
            set {
                this.memberMobilePhoneNumberIsValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchMemberAccountPhoneNumberCompletedEventHandler(object sender, FetchMemberAccountPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchMemberAccountPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchMemberAccountPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchMemberAccountPhoneNumberReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchMemberAccountPhoneNumberReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchMemberMobilePhoneNumberCompletedEventHandler(object sender, FetchMemberMobilePhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchMemberMobilePhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchMemberMobilePhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchMemberMobilePhoneNumberReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchMemberMobilePhoneNumberReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchMemberPhoneNumbersCompletedEventHandler(object sender, FetchMemberPhoneNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchMemberPhoneNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchMemberPhoneNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchMemberPhoneNumbersReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchMemberPhoneNumbersReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchMemberEmailAddressCompletedEventHandler(object sender, FetchMemberEmailAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchMemberEmailAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchMemberEmailAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchMemberEmailAddressReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchMemberEmailAddressReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchAddressCountryListCompletedEventHandler(object sender, FetchAddressCountryListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchAddressCountryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchAddressCountryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchAddressCountryListReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchAddressCountryListReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchAddressRegionListCompletedEventHandler(object sender, FetchAddressRegionListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchAddressRegionListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchAddressRegionListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchAddressRegionListReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchAddressRegionListReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveMemberEmailAddressCompletedEventHandler(object sender, SaveMemberEmailAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMemberEmailAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMemberEmailAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveMemberEmailAddressReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveMemberEmailAddressReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveMemberAccountPhoneNumberCompletedEventHandler(object sender, SaveMemberAccountPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMemberAccountPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMemberAccountPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveMemberAccountPhoneNumberReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveMemberAccountPhoneNumberReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveMemberMobilePhoneNumberCompletedEventHandler(object sender, SaveMemberMobilePhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMemberMobilePhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMemberMobilePhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveMemberMobilePhoneNumberReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveMemberMobilePhoneNumberReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveMemberPhoneNumbersCompletedEventHandler(object sender, SaveMemberPhoneNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMemberPhoneNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMemberPhoneNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveMemberPhoneNumbersReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveMemberPhoneNumbersReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchMemberPostalAddressCompletedEventHandler(object sender, FetchMemberPostalAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchMemberPostalAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchMemberPostalAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchMemberPostalAddressReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchMemberPostalAddressReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FetchMemberContactInfoCompletedEventHandler(object sender, FetchMemberContactInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchMemberContactInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchMemberContactInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchMemberContactInfoReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchMemberContactInfoReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveMemberPostalAddressCompletedEventHandler(object sender, SaveMemberPostalAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMemberPostalAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMemberPostalAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveMemberPostalAddressReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveMemberPostalAddressReturn)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591